project:
  type: website
  output-dir: docs
  
website: 
  title: "My Personal website"
  
  navbar:
    left:  
      - text: "About ME!"     
        href: Introduction.qmd  
      - text: "My Interests"
        href: Hobbies.qmd

format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true
    toc-location: left