project:
  type: website

website:
  title: "About ME"
  navbar:
    left:  
      - text: "About ME!"     
        href: "index.html"  
      - text: "Interests"
        href: "Interests.html"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
