project:
  type: website

website:
  title: "My Personal Website"
  navbar:
    left:
      - text: "About Me"
        href: "index.qmd"          
      - text: "My Interests"
        href: "My Interests.qmd"   
theme: "cosmo"
