project:
  type: website
output-dir: _site
website:
  navbar:
    left:  
      - text: "About ME!"     
        href: index.qmd  
      - text: "My Interests"
        href: My Interests.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    

